### ISSUE TITLE
Client Uptade Server ini Register Button Active

### ISSUE THREAD

**Issue by KnightGuard-KO** [ko4life-net/ko#126]
GameProcLogin.cpp

120 - Add Codes

	char szRegistrationSite[_MAX_PATH];
	memset(szRegistrationSite, 0, sizeof(szRegistrationSite));

	GetPrivateProfileString("Join", "Registration site", "", szRegistrationSite, _MAX_PATH, szIniPath);
	m_szRegistrationSite = std::string(szRegistrationSite);

124 - Until Codes

GameProcLogin.h

19 - Add Codes

	std::string		m_szRegistrationSite;

UILogin.cpp 

72 - Add Codes

else if (pSender == m_pBtn_Join)
		{
			if (!CGameProcedure::s_pProcLogIn->m_szRegistrationSite.empty())
			{
				ShellExecute(NULL, "open", CGameProcedure::s_pProcLogIn->m_szRegistrationSite.c_str(), NULL, NULL, SW_SHOWNORMAL);
			}

			return true;
		}
80 - Until Codes

Thanks Knight Online His  Family

**Comment by GiRx8** [comment]
From my understanding this is to add a link to the registration button on login menu via the server.ini in client? why did you submit this as an issue?

**Comment by BenimSource** [comment]
My Server.ini Example

[Join]
Registration site=http://www.yourname.com/register.php

**Comment by BenimSource** [comment]
After Entering the Codes That I Have Given Properly
Log in to the Game Click on the Register Button

**Comment by GiRx8** [comment]
Yeah I get that, but why didn’t you submit the code instead of opening an issue?

**Comment by GiRx8** [comment]
i'll test this and add it for you.

**Comment by KnightGuard-KO** [comment]
thanks man

I'm glad I could help
