### ISSUE TITLE
When exiting the game, character data is not being saved

### ISSUE THREAD

**Issue by stevewgr** [ko4life-net/ko#132]
#### Description

When exiting the game, character data is not being saved.

This could be either server side code issue or most likely a stored procedure.

#### To Reproduce

1. Create character
2. Level up
3. Exit the game
4. Login back

You'll start over.

#### Tasks

- [x] Fix character saving issue when exiting the game

**Comment by stevewgr** [comment]
@xGuTeK already have it fixed and this is currently pending for a PR.

**Comment by srmeier** [comment]
@stevewgr @xGuTeK  Which PR is this?

**Comment by stevewgr** [comment]
> @stevewgr @xGuTeK Which PR is this?

There was no PR unfortunately. @xGuTeK mentioned to me back then in regards to some of the tickets that he had fixed some of them, but these were local changes that he never pushed remotely. Feel free to take over if you see similar comments.

**Comment by stevewgr** [comment]
I unassigned him from the other tickets as well just to avoid confusion.

**Comment by srmeier** [comment]
@stevewgr Would assign this one to @selcukcukur. He has done some work here #200 and I assume he will open new PRs to address this issue.

**Comment by selcukcukur** [comment]
You can find the fix for the issue here. #201

**Comment by stevewgr** [comment]
This ticket was solved part of this ticket: https://github.com/ko4life-net/ko/issues/94
