### ISSUE TITLE
Looting item bundle causes the game to crash

### ISSUE THREAD

**Issue by stevewgr** [ko4life-net/ko#135]
#### Description

Looting item bundle causes the game to crash.

Official behavior always provide at least one item, which is coins.

#### To Reproduce

1. Kill a monster
2. Try to loot item

Client will crash.

#### Tasks

- [x] Check whether packet receive or send works correctly, if yes, enforce the default first item to always be coins.

**Comment by xGuTeK** [comment]
I have fixed this issue already it will be pulled in my next PR

**Comment by stevewgr** [comment]
Still pending for a PR. The fix though is simple; changing item table ext constant to 23, but given that @xGuTeK already fixed it, let's wait for his PR.

**Comment by stevewgr** [comment]
This issue was fixed in this PR by @srmeier: https://github.com/ko4life-net/ko/pull/174
